// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScan(arg1) {
  return window['go']['scan']['API']['GetScan'](arg1);
}

export function ListScans() {
  return window['go']['scan']['API']['ListScans']();
}

export function Scan(arg1) {
  return window['go']['scan']['API']['Scan'](arg1);
}

export function ScanNonRecursive(arg1) {
  return window['go']['scan']['API']['ScanNonRecursive'](arg1);
}

export function SetContext(arg1) {
  return window['go']['scan']['API']['SetContext'](arg1);
}

export function UpdateScanStatus(arg1, arg2) {
  return window['go']['scan']['API']['UpdateScanStatus'](arg1, arg2);
}
