// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Scan(arg1) {
  return window['go']['scan']['API']['Scan'](arg1);
}

export function ScanNonRecursive(arg1) {
  return window['go']['scan']['API']['ScanNonRecursive'](arg1);
}
