// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function GetScan(arg1:string):Promise<entity.DirEntry>;

export function ListScans():Promise<Array<entity.ScanSummary>>;

export function Scan(arg1:string):Promise<entity.DirEntry>;

export function ScanNonRecursive(arg1:string):Promise<entity.DirEntry>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateScanStatus(arg1:string,arg2:string):Promise<void>;
