// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function DeleteItems(arg1:entity.DeletionRequest):Promise<entity.DeletionSummary>;

export function GetDeletionHistory():Promise<Array<entity.DeletionSummary>>;

export function GetScan(arg1:string):Promise<entity.DirEntry>;

export function GetSystemDiskUsage():Promise<entity.DiskStats>;

export function ListDrives():Promise<Array<string>>;

export function ListScans():Promise<Array<entity.ScanSummary>>;

export function Scan(arg1:string):Promise<entity.DirEntry>;

export function ScanNonRecursive(arg1:string):Promise<entity.DirEntry>;
