// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function GetScan(arg1:string):Promise<entity.DirEntry>;

export function ListScans():Promise<Array<entity.ScanSummary>>;

export function Scan(arg1:string):Promise<entity.DirEntry>;

export function ScanNonRecursive(arg1:string):Promise<entity.DirEntry>;
