// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScan(arg1) {
  return window['go']['main']['App']['GetScan'](arg1);
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function ListScans() {
  return window['go']['main']['App']['ListScans']();
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function ScanNonRecursive(arg1) {
  return window['go']['main']['App']['ScanNonRecursive'](arg1);
}
